version: "3"

services:
  # go application container
  ## コマンドとして使うことを想定
  ## $ docker-compose run --rm go ...
  go:
    build: . # ./Dockerfile をビルド
    entrypoint:
      - go
    volumes:
      # ./ => docker://app:/go/ にマウント
      - ./:/go/
    environment:
      # TimeZone を Asia/Tokyo に
      TZ: Asia/Tokyo
